name: build-macos
on: [push]
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install cmake
      - run: python -m pip install "protobuf"
      - run: cmake --version
      - run: python --version
